name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload jar
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
      uses: actions/upload-artifact@v4
      with:
        name: jar-file
        path: build/libs/*.jar
